version: "1.0"
info:
  model: int-scaffold
packages:
- name: SIQA_GIT_0812Project
  gitServerName: rimaSCName
  gitUrl: https://github.com/rimabarman
  gitUsername: rimabarman
  gitBranch: main
- name: WmSalesforceRESTProvider
  version: 10.7.0.0.197
  wpmServer: https://packages.webmethods.io
  wpmRegistry: supported
- name: SIQAJDBCAdapterTests
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
- name: DADA_GlobalVariable1
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
- name: SIQACloudStreamsTests
  version: "1.0"
  gitServerName: rimaSCName
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: rimabarman
  gitBranch: main
services:
- serviceName: project.siqa_git_0812.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.connections:MyConnAlias
  packages:
  - name: SIQA_GIT_0812Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.197
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_0812.integrations:TestRestConnector
  packages:
  - name: SIQA_GIT_0812Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.197
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_0812.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.operations.actions:TestRest
  packages:
  - name: SIQA_GIT_0812Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.197
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: project.siqa_git_0812.integrations:deepclonetest
  packages:
  - name: SIQA_GIT_0812Project
    version: "1.0"
  - name: DADA_GlobalVariable1
    version: "1.0"
  - name: SIQAJDBCAdapterTests
    version: "1.0"
  - name: WmJDBCAdapter
    version: 10.3.0.0.34
    wpmServer: https://packages.webmethods.io
    wpmRegistry: licensed
  - name: WmSalesforceProvider
    version: 10.7.0.0.71
  - name: WmSalesforceRESTProvider
    version: 10.7.0.0.197
  - name: SIQACloudStreamsTests
    version: "1.0"
- serviceName: pub.string:stringToBytes
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.utils:deepClone
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
- serviceName: pub.string:bytesToString
  packages:
  - name: WmPublic
    version: 11.1.0.0.2105
configurationVariables:
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.hostnameVerifier
  : org.apache.http.conn.ssl.DefaultHostnameVerifier
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.authorizationHeaderPrefix
  : Bearer
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.keepAliveInterval
  : "300000"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.timeoutType
  : auto
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.sockBuffSize
  : "8192"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.enableSNI
  : "true"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cx.grant_type
  : refresh_token
  ? iscloudstreamsconnectorservice.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..operations..actions:TestRest.virtualServiceName
  : WmCloudStreams.RestVS
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.refreshAccessToken
  : "true"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.accessTokenRefreshURL
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.authorizationServerUrl
  : https://login.salesforce.com/services/oauth2/authorize
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.retryCount
  : "4"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth.consumerSecret
  : "{AES}ePv9vDKXdd6A2HDsPDBAO8y1Fe9R7m6Dya5xSCLlAK353vKmgg/uiZT0YAoUU42Eojf9A5EvRE+pSL3aLrpBNWmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.scope
  : offline_access api refresh_token
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.refreshToken
  : "{AES}z0OyKRGMCuSrw5+VwAKX9/oM6BIKjPeYnDaBN96E5WE51ihADTbuVPxNgEzibj4QruD7dprkqIUz2A2UuAroPCo9lkD9cn9+IyICeILx3/1l3xiIkjokSOR4joVg6CJF"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.startupBackoffSecs
  : "10"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.tcpNoDelay
  : "false"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.poolIncrementSize
  : "1"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.startupRetryCount
  : "0"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.blockTimeout
  : "1000"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.authorizationHeaderInTokenRefresh
  : "false"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.providerUrl
  : https://sag53-dev-ed.develop.my.salesforce.com
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.retryIfRequestSentOk
  : "true"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.idleTimeout
  : "-1"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.maximumPoolSize
  : "10"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.readTimeout
  : "30000"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.minimumPoolSize
  : "1"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.enableCompression
  : "false"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.expireTimeout
  : "1000"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.connectTimeout
  : "30000"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.reuseAddr
  : "false"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.accessTokenRefreshURLRequest
  : URL Query String
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth_v20.authenticationServerUrl
  : https://login.salesforce.com/services/oauth2/token
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth.accessToken
  : "{AES}h1r1CmTvU65r25EqPgWKVSkYwQTSYXmOR3toVVhlcOtbtuMWJ8zNOmw2bpkjmijOJLO+NbhvQYPFUKD1lM/Rr+CRS+YoeqRon7RecTx2zQu9QcZ+ZRkHTfzmc/PTnMRaJfFqlx7yDZkz6kmCGDq0IWmK1wuN3U1rA1B0VhuZoUw="
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.validateAfterInactivity
  : "1000"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.socketStaleCheck
  : "true"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.oauth.consumerId
  : 3MVG9k02hQhyUgQCKlnwOVc1lTfY9AqPHmUIRA6I.ZqYzln.F3Vuok.Rk6d6F00IhbOJxstGzhIJDyuJGd0ft
  ? iscloudstreamsconnectorservice.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..operations..actions:TestRest.connectionAlias
  : project.siqa_git_0812.WmSalesforceRESTProvider.com_softwareag_cloudstreams_salesforce_rest_v60.connections:MyConnAlias
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.cn.socketLinger
  : "-1"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.poolable
  : "true"
  ? cloudstreamsconnection.project..siqa_git_0812..WmSalesforceRESTProvider..com_softwareag_cloudstreams_salesforce_rest_v60..connections:MyConnAlias.connectionEnabled
  : "true"
